In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df1 = pd.read_csv("/mnt/c/Office 2019/DS_PW/DL_Practice/Fake_Email_Detector/dataset/raw_data/CEAS_08.csv")
df2 = pd.read_csv("/mnt/c/Office 2019/DS_PW/DL_Practice/Fake_Email_Detector/dataset/raw_data/email.csv")
df3 = pd.read_csv("/mnt/c/Office 2019/DS_PW/DL_Practice/Fake_Email_Detector/dataset/raw_data/Phishing_Email.csv")

In [3]:
df1 = df1[['body','label']]
df1

                                                    body  label
0      Buck up, your troubles caused by small dimensi...      1
1      \nUpgrade your sex and pleasures with these te...      1
2      >+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...      1
3      Would anyone object to removing .so from this ...      0
4      \nWelcomeFastShippingCustomerSupport\nhttp://7...      1
...                                                  ...    ...
39149  \n\nCNN Alerts: My Custom Alert\n\n\n\n\n\n\n ...      1
39150  \n\nCNN Alerts: My Custom Alert\n\n\n\n\n\n\n ...      1
39151  Hello there ! \nGreat work on the slide show v...      0
39152  \nMail from sender , coming from intuit.com\ns...      0
39153  Dear fellow Pythonistas!\n\nGuido has accepted...      0

[39154 rows x 2 columns]

In [4]:
df2 = df2.iloc[:5572]
df2

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df3

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email
...,...,...,...
18645,18646,date a lonely housewife always wanted to date ...,Phishing Email
18646,18647,request submitted : access request for anita ....,Safe Email
18647,18648,"re : important - prc mtg hi dorn & john , as y...",Safe Email
18648,18649,press clippings - letter on californian utilit...,Safe Email
18649,18650,empty,Phishing Email

In [6]:
df1['label'] = df1.label.apply(lambda x: 'Spam' if x == 1 else "Safe")
df1

                                                    body label
0      Buck up, your troubles caused by small dimensi...  Spam
1      \nUpgrade your sex and pleasures with these te...  Spam
2      >+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...  Spam
3      Would anyone object to removing .so from this ...  Safe
4      \nWelcomeFastShippingCustomerSupport\nhttp://7...  Spam
...                                                  ...   ...
39149  \n\nCNN Alerts: My Custom Alert\n\n\n\n\n\n\n ...  Spam
39150  \n\nCNN Alerts: My Custom Alert\n\n\n\n\n\n\n ...  Spam
39151  Hello there ! \nGreat work on the slide show v...  Safe
39152  \nMail from sender , coming from intuit.com\ns...  Safe
39153  Dear fellow Pythonistas!\n\nGuido has accepted...  Safe

[39154 rows x 2 columns]

In [7]:
df2["body"] = df2['Message']
df2['label'] = df2['Category'].apply(lambda x: 'Spam' if x == 'spam' else "Safe")

In [8]:
df2.drop("Category",axis = 1,inplace = True)
df2.drop("Message",axis = 1,inplace = True)
df2

                                                   body label
0     Go until jurong point, crazy.. Available only ...  Safe
1                         Ok lar... Joking wif u oni...  Safe
2     Free entry in 2 a wkly comp to win FA Cup fina...  Spam
3     U dun say so early hor... U c already then say...  Safe
4     Nah I don't think he goes to usf, he lives aro...  Safe
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...  Spam
5568               Will ü b going to esplanade fr home?  Safe
5569  Pity, * was in mood for that. So...any other s...  Safe
5570  The guy did some bitching but I acted like i'd...  Safe
5571                         Rofl. Its true to its name  Safe

[5572 rows x 2 columns]

In [9]:
df3.columns

Index(['Unnamed: 0', 'Email Text', 'Email Type'], dtype='str')

In [10]:
df3['body'] = df3['Email Text']
df3['label'] = df3["Email Type"].apply(lambda x: 'Spam' if x == 1 else "Safe")
df3.drop(['Unnamed: 0', 'Email Text', 'Email Type'],axis =1,inplace = True)
df3

                                                    body label
0      re : 6 . 1100 , disc : uniformitarianism , re ...  Safe
1      the other side of * galicismos * * galicismo *...  Safe
2      re : equistar deal tickets are you still avail...  Safe
3      \nHello I am your hot lil horny toy.\n    I am...  Safe
4      software at incredibly low prices ( 86 % lower...  Safe
...                                                  ...   ...
18645  date a lonely housewife always wanted to date ...  Safe
18646  request submitted : access request for anita ....  Safe
18647  re : important - prc mtg hi dorn & john , as y...  Safe
18648  press clippings - letter on californian utilit...  Safe
18649                                              empty  Safe

[18650 rows x 2 columns]

In [11]:
df = pd.concat([df1,df2,df3])

In [12]:
df.to_csv("/mnt/c/Office 2019/DS_PW/DL_Practice/Fake_Email_Detector/dataset/clean_data/spam_email.csv",index=False)